version: 2.1
orbs:
  khq-stitch-function:  kubra/khq-stitch-function@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.1
  tools: signavio/tools-orb@0.5.0
  khq-app-build: kubra/khq-app-build@0

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

workflows:
  test-deploy:
    jobs:
      - command-test:
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb_name: kubra/khq-stitch-function
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
            - command-test
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
