description: >
  Uses the CircleCI hosted base stable image

docker:
  - image: cimg/base:stable

resource_class: << parameters.resource-class >>

parameters:
  resource-class:
    default: medium
    description: >
      The size of the container to run the job in.
      Refer to https://circleci.com/docs/configuration-reference/#docker-execution-environment for sizes
    type: string